
services:
  miresiliencia:
    restart: unless-stopped
    ports:
      - "8080:80"
    image: "geotestch/miresiliencia:latest"
    container_name: mires
    environment:
      "Environment:DBHost": "your.dbserver.com"
      "Environment:DB": "miresilienciadb"
      "Environment:DBUser": "miresiliencia"
      "Environment:DBPassword": "yourpassword"
      "Environment:SplittingBehavior": "true"
      "Environment:Geoserver": "your.geoserver.com"
